apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy
  namespace: monitoring
  labels:
    app: nginx-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-proxy
  template:
    metadata:
      labels:
        app: nginx-proxy
    spec:
      containers:
      - name: nginx
        command:
          - /bin/sh
          - -c
          - |-
            nginx -g 'daemon off;'
        image: alibaba-cloud-linux-3-registry.cn-hangzhou.cr.aliyuncs.com/alinux3/nginx_optimized:20240221-1.20.1-2.3.0
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-proxy-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-proxy-config
  namespace: monitoring
data:
  default.conf: |
    server {
        listen 80;
        
        location / {
            proxy_pass http://10.0.193.71:10254;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy
  namespace: monitoring
  labels:
    app: nginx-proxy
spec:
  ports:
  - port: 80
    targetPort: 80
    name: http
  selector:
    app: nginx-proxy 
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: ack-prometheus-operator
  name: nginx-proxy
  namespace: monitoring
spec:
  endpoints:
  - targetPort: 80
  selector:
    matchLabels:
      app: nginx-proxy
  namespaceSelector:
    matchNames: 
      - monitoring
