apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-web-nginx-config
data:
  default.conf: |
    server {
        listen 80;
{{ range .Values.ingress.path }}
        location {{ . }} {
            alias /var/www/;
            index index.html;
            try_files $uri $uri/ /index.html;
        }
{{ end }}
    }

