{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
        {{ range .Values.ingress.path }}
          - path: {{ . }}
            pathType: Prefix
            backend:
              service:
                name: svc-{{ $.Release.Name }}
                port:
                  number: {{ $.Values.port }}
        {{ end }}
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: secret-https-wis.com
{{- end }}

